/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package se.gui;

/**
 *
 * @author braya
 */

import se.util.MathUtils;
import javax.swing.*;
import java.awt.*;

public class VentanaPrincipal extends javax.swing.JFrame {
    private JTextField txtTotal;
    private JTextField txtFavorables;
    private JLabel lblResultado;
    private JButton btnCalcular;
    
    public VentanaPrincipal() {
        initComponents();
        inicializarComponentes();
    }
    
    private void inicializarComponentes() {
        setTitle("Implementación ID3");
        setSize(500, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Panel para cálculo de entropía básica
        JPanel panelEntropiaBasica = new JPanel();
        panelEntropiaBasica.setLayout(new GridLayout(4, 2, 10, 10));
        panelEntropiaBasica.setBorder(BorderFactory.createTitledBorder("Cálculo de Entropía Básica"));
        
        // Componentes
        panelEntropiaBasica.add(new JLabel("Total de casos (n):"));
        txtTotal = new JTextField();
        panelEntropiaBasica.add(txtTotal);
        
        panelEntropiaBasica.add(new JLabel("Casos favorables:"));
        txtFavorables = new JTextField();
        panelEntropiaBasica.add(txtFavorables);
        
        btnCalcular = new JButton("Calcular");
        panelEntropiaBasica.add(btnCalcular);
        
        lblResultado = new JLabel("Resultado: ");
        panelEntropiaBasica.add(lblResultado);
        
        // Evento del botón
        btnCalcular.addActionListener(e -> calcularEntropia());
        
        // Agregar panel al frame
        setLayout(new BorderLayout());
        add(panelEntropiaBasica, BorderLayout.CENTER);
    }
    
    private void calcularEntropia() {
        try {
            int total = Integer.parseInt(txtTotal.getText().trim());
            int favorables = Integer.parseInt(txtFavorables.getText().trim());
            
            if (favorables > total) {
                JOptionPane.showMessageDialog(this, 
                    "Los casos favorables no pueden ser mayores que el total",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            double entropia = MathUtils.calcularEntropiaBinaria(total, favorables);
            lblResultado.setText(String.format("Entropía = %.4f", entropia));
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Por favor ingrese números válidos",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
